name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Installer les libs locales dans le repo Maven de l'agent
      - name: Install gpsUtil
        run: mvn install:install-file -Dfile=TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar

      - name: Install tripPricer
        run: mvn install:install-file -Dfile=TourGuide/libs/tripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

      - name: Install rewardCentral
        run: mvn install:install-file -Dfile=TourGuide/libs/rewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

      - name: Compile
        run: mvn compile -B --file TourGuide/pom.xml

      - name: Run unit tests
        run: mvn test -B -DskipITs=true -DskipPerformanceTests=true --file TourGuide/pom.xml

      - name: Package JAR
        run: mvn package -B -DskipTests --file TourGuide/pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: TourGuide/target/*.jar

