name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile
        run: mvn compile -B --file TourGuide/pom.xml

      - name: Run unit tests
        run: mvn test -B -DskipITs=true -DskipPerformanceTests=true --file TourGuide/pom.xml

      - name: Package JAR
        run: mvn package -B -DskipTests --file TourGuide/pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
